### ISSUE TITLE
Timezone issue

### ISSUE THREAD

**Issue by gitasmus** [shiaky/breitbandmessung#11]
Be careful to use the correct timezone, e.g., run via
docker run -e TZ="Europe/Stockholm" -v $PWD/messprotokolle:/export/ shiaky/breitbandmessung:latest

**Comment by nillebor** [comment]
Timezone works here fine.
Testet on Synology Diskstation.

**Comment by shiaky** [comment]
Added the timezone to the Dockerimage now.
