### ISSUE TITLE
Raspberry Support?

### ISSUE THREAD

**Issue by pata-fix** [shiaky/breitbandmessung#3]
Hi,
will there be compatibility for the ARM architecture? I would like to run this on a Raspberry PI.
Regards
Pat
#question 

`Status: Downloaded newer image for shiaky/breitbandmessung:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
standard_init_linux.go:228: exec user process caused: exec format error`

**Comment by shiaky** [comment]
Hi pata,

I can have a look on it, but I'm not sure how to build a docker image for arm currently. Please give me some weeks to find this out and supply an arm version.

**Comment by shiaky** [comment]
Hi pata,
I created _arm64_ and _arm7_ images. Since I have no arm device at hand please give it a try and let me know whether it runs as expected.

Cheers

**Comment by shiaky** [comment]
I close this for now. Please feel free to open it again if you encounter any problems.
